### ISSUE TITLE
Incorrect names for input parameters

### ISSUE THREAD

**Issue by gasgithub** [IBM/satellite-config-upload-action#9]
Parameters  'channelUuid', 'versionName' in Readme.md are incorrect.
While running action from readme I'm getting following error:
```
Unexpected input(s) 'channelUuid', 'versionName', valid inputs are ['apikey', 'channel_id', 'filename', 'version_name']
```

**Comment by adamkingit** [comment]
Judging by #10 the readme needs to be updated, but you can already updated your usage to progress. We'll work on the doc.

**Comment by knguyen100000010** [comment]
Flaws during release:

In `v1` version, `['apikey', 'channel_id', 'filename', 'version_name']` are used: https://github.com/IBM/satellite-config-upload-action/blob/v1/action.yml

In `v1-alpha*`, the above variable names are changed to what mentioned in the [README](https://github.com/IBM/satellite-config-upload-action#readme)

Short-term solution: Follow the README and use `IBM/satellite-config-actions@v1alpha4`

**Comment by knguyen100000010** [comment]
#13

**Comment by knguyen100000010** [comment]
I'm going to close this issue since the fix has been released
